apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  username: bXl1c2Vy
kind: Secret
metadata:
  labels:
    pg-cluster: "{{.Values.cluster_name }}"
  name: "{{.Values.cluster_name}}-otheruser-secret"
  namespace: "{{.Values.namespace}}"
type: Opaque
