apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  labels:
    archive: 'false'
    archive-timeout: '60'
    crunchy-pgbadger: 'false'
    crunchy_collect: 'false'
    current-primary: "{{.Values.cluster_name}}"
    deployment-name: "{{.Values.cluster_name}}"
    name: "{{.Values.cluster_name}}"
    pg-cluster: "{{.Values.cluster_name}}"
    pgo-backrest: 'true'
    pgo-version: 4.3.0
    primary: 'true'
  annotations:
    current-primary: "{{.Values.cluster_name}}"
  name: "{{.Values.cluster_name}}"
  namespace: wateringhole
spec:
  ArchiveStorage:
    accessmode: ''
    fsgroup: '26'
    matchLabels: ''
    name: ''
    size: ''
    storageclass: azure-rwo
    storagetype: dynamic
    supplementalgroups: ''
  BackrestStorage:
    accessmode: ReadWriteOnce
    fsgroup: '26'
    matchLabels: ''
    name: ''
    size: 1G
    storageclass: azure-rwo
    storagetype: dynamic
    supplementalgroups: ''
  ContainerResources:
    limitscpu: ''
    limitsmemory: ''
    requestscpu: ''
    requestsmemory: ''
  PrimaryStorage:
    accessmode: ReadWriteOnce
    fsgroup: '26'
    matchLabels: ''
    name: crdcluster
    size: 1G
    storageclass: azure-rwo
    storagetype: dynamic
    supplementalgroups: ''
  ReplicaStorage:
    accessmode: ReadWriteOnce
    fsgroup: '26'
    matchLabels: ''
    name: ''
    size: 1G
    storageclass: azure-rwo
    storagetype: dynamic
    supplementalgroups: ''
  backuppath: ''
  backuppvcname: ''
  ccpimage: crunchy-postgres-ha
  ccpimagetag: centos7-12.2-4.3.0
  clustername: "{{.Values.cluster_name}}"
  customconfig: ''
  database: mydb
  name: "{{.Values.cluster_name}}"
  namespace: wateringhole
  nodename: ''
  policies: ''
  port: '5432'
  primaryhost: "{{.Values.cluster_name}}"
  primarysecretname: "{{.Values.cluster_name}}-primaryuser-secret"
  replicas: '0'
  rootsecretname: "{{.Values.cluster_name}}-postgres-secret"
  secretfrom: ''
  status: ''
  strategy: '1'
  user: myuser
  userlabels:
    archive: 'false'
    archive-timeout: '60'
    crunchy-pgbadger: 'false'
    crunchy_collect: 'false'
    pgo-backrest: 'true'
    pgo-version: 4.3.0
  usersecretname: "{{.Values.cluster_name}}-otheruser-secret"
