apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  username: cHJpbWFyeXVzZXI=
kind: Secret
metadata:
  labels:
    pg-cluster: "{{.Values.cluster_name }}"
  name: "{{.Values.cluster_name}}-primaryuser-secret"
  namespace: "{{.Values.namespace}}"
type: Opaque
