kind: Deployment
apiVersion: apps/v1
metadata:
  name: gpu-test
  namespace: gpu-test
  labels:
    app: cloudlet
    app.kubernetes.io/component: cloudlet
    app.kubernetes.io/instance: cloudlet
    app.kubernetes.io/part-of: cloudlet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudlet
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cloudlet
        deploymentconfig: cloudlet
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: cloudlet
          image: {{ .Values.containers.repository }}/{{ .Values.containers.image }}:{{ .Values.containers.version }} 
          ports: 
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
