apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: "{{APICAST_NAME}}"
spec:
  replicas: 2
  selector:
    deploymentconfig: "{{APICAST_NAME}}"
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        deploymentconfig: "{{APICAST_NAME}}"
    spec:
      containers:
      - env:
        - name: THREESCALE_PORTAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: "{{CONFIGURATION_URL_SECRET}}"
              key: password
        - name: THREESCALE_CONFIG_FILE
          value: "{{CONFIGURATION_FILE_PATH}}"
        - name: THREESCALE_DEPLOYMENT_ENV
          value: "{{DEPLOYMENT_ENVIRONMENT}}"
        - name: RESOLVER
          value: "{{RESOLVER}}"
        - name: APICAST_SERVICES_LIST
          value: "{{SERVICES_LIST}}"
        - name: APICAST_CONFIGURATION_LOADER
          value: "{{CONFIGURATION_LOADER}}"
        - name: APICAST_LOG_LEVEL
          value: "{{LOG_LEVEL}}"
        - name: APICAST_PATH_ROUTING
          value: "{{PATH_ROUTING}}"
        - name: APICAST_RESPONSE_CODES
          value: "{{RESPONSE_CODES}}"
        - name: APICAST_CONFIGURATION_CACHE
          value: "{{CONFIGURATION_CACHE}}"
        - name: REDIS_URL
          value: "{{REDIS_URL}}"
        - name: APICAST_MANAGEMENT_API
          value: "{{MANAGEMENT_API}}"
        - name: OPENSSL_VERIFY
          value: "{{OPENSSL_VERIFY}}"
        - name: APICAST_REPORTING_THREADS
          value: "{{REPORTING_THREADS}}"
        - name: APICAST_WORKERS
          value: "{{APICAST_WORKERS}}"
        image: "{{IMAGE_NAME}}"
        imagePullPolicy: Always
        name: "{{APICAST_NAME}}"
        livenessProbe:
          httpGet:
            path: /status/live
            port: management
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /status/ready
            port: management
          initialDelaySeconds: 15
          timeoutSeconds: 1
        ports:
        - name: proxy
          containerPort: 8080
          protocol: TCP
        - name: management
          containerPort: 8090
          protocol: TCP
  triggers:
  - type: ConfigChange
{{ end }}
