apiVersion: v1
kind: Service
metadata:
  name: speedtest-upload
  namespace: speedtest-cloudapp
spec:
  type: NodePort
  selector:
    app: speedtest-upload
  ports:
    - name: speedtest-upload
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30038
