apiVersion: v1
kind: Secret
data:
  FirstName: {{ .Values.opsmanageradmin.FirstName | toString | b64enc }}
  LastName: {{ .Values.opsmanageradmin.LastName | toString | b64enc }}
  Password: {{ .Values.opsmanageradmin.Password | toString | b64enc }}
  Username: {{ .Values.opsmanageradmin.Username | toString |b64enc }}
metadata:
  name: opsmanageradmin
  namespace: {{ .Values.namespace }}
type: Opaque
