---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    application: opsmanager
  name: opsmanager
  namespace: {{ .Values.namespace }}
spec:
  port:
    targetPort: mongodb
  to:
    kind: Service
    name: mongodb-opsmanager-svc
    weight: 100
  wildcardPolicy: None
