kind: Service
apiVersion: v1
metadata:
  name: "monitoring-service"
  namespace: "{{ .Values.namespace }}"
  labels:
    component: pmm
    app: monitoring
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    component: pmm
    app: monitoring
  type: {{ .Values.service.type | quote }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
