kind: Deployment
apiVersion: apps/v1
metadata:
  name: argo-to-splunk
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-to-splunk
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argo-to-splunk
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: argo-to-splunk
            defaultMode: 420
      containers:
        - name: argo-to-splunk
          image: >-
            image-registry.openshift-image-registry.svc:5000/argocd/cloudlet:argo-to-splunk
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /argocd_to_splunk/src/config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
