apiVersion: v1
kind: Service
metadata:
  name: speedtest-cloudapp-service
  namespace: speedtest-cloudapp
spec:
  selector:
    app: speedtest-cloudapp
  ports:
    - name: speedtest-cloudapp-service
      protocol: TCP
      port: 8000
      targetPort: 8000

