---

- name: "Run postjobs for Quay installation"
  hosts: localhost
  gather_facts: no
  become: false
  tasks:

#    - name: "Create cloudlet Organization"
#      uri:
#        url: "{{ QUAY_ENDPOINT }}/api/v1/organization/"
#        method: POST
#        headers:
#          Authorization: "Bearer {{ QUAY_AUTH_TOKEN }}"
#        validate_certs: no #delete when certs are trusted
#        body_format: json
#        status_code: 201
#        body:
#          name: "{{ organization }}"
#
#    - name: "Create mgmt (managment) OAuth Application under cloudlet org"
#      uri:
#          url: "{{ QUAY_ENDPOINT }}/api/v1/organization/{{ organization }}/applications"
#          method: POST
#          headers:
#            Authorization: "Bearer {{ QUAY_AUTH_TOKEN }}"
#          validate_certs: no #delete when certs are trusted
#          body_format: json
#          status_code: 201
#          body:
#            name: "mgmt"

    - name: "Update Quay Configuration"
      shell: oc login https://api.ocp43-prod.sales.lab.tlv.redhat.com:6443 -uadmin -predhat -n quay-enterprise --insecure-skip-tls-verify=true
 
    - name: "Create temporary directory"
      tempfile:
        state: directory
      register: tempdir
 
    - name: "Get current Configuration"
      shell: "oc extract secret/quay-enterprise-config-secret --to={{ tempdir.path }} --keys=config.yaml"

    - name: "Modify Configuration"
      include_vars:
        file: "{{ tempdir.path }}/config.yaml"
        name: default_config
      
    - template:
        src: config.yaml.j2
        dest: "{{ tempdir.path }}/config.yaml"
  
    - name: "Apply new Configuration"
      shell: "oc delete secret quayconfigfile"
      ignore_errors: true

    - shell: "oc create secret generic quayconfigfile --from-file={{ tempdir.path }}/config.yaml"
  
    - name: "Remove temporary directory"
      file:
        path: "{{ tempfile.path }}"
        state: absent
      when: tempfile.path is defined

#    - name: "White list mgmt client-id in Quay's configuration"
       
    - name: "Rollout Quay deployment"
      shell: "oc rollout restart deployment {{ item }}"
      with_items:
        - "quayecosystem-quay"
        - "quayecosystem-quay-repomirror"
  
#    - name: "Generate OAuth Token with admin scopre"
  
#    - name: "Uploud Token to OCP as a secret in Quay's Project"
  
    - name: "Create cloudlet+mirror robot for mirroing of all applications"
      uri:
        url: "{{ QUAY_ENDPOINT }}/api/v1/organization/{{ organization }}/robots/{{ robot_username }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ QUAY_AUTH_TOKEN }}"
        validate_certs: no
        body_format: json
        status_code: 201
        body:
          description: "Robot for mirroring"
      ignore_errors: true
      register: robot

    - name: "Generate pullsecret from robot"
      
