apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: minio-test
  namespace: minio-test
spec:
  schedule: '0 * * * *'
  replicas: 1
  jobTemplate:
    metadata:
      labels:
        app: minio-test
    spec:
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: minio-test
                defaultMode: 420
          containers:
            - name: minio-test
              image: '{{ .Values.containers.repository }}/{{ .Values.containers.image }}:{{ .Values.containers.version }}'
              resources: {}
              volumeMounts:
                - name: config-volume
                  mountPath: /minio-test/src/config
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
      progressDeadlineSeconds: 600
