apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
type: Opaque
data:
  accesskey: bWluaW8= # base 64 encoded "minio" (echo -n 'minio' | base64)
  secretkey: bWluaW8xMjM= # based 64 encoded "minio123" (echo -n 'minio123' | base64)
---
apiVersion: miniocontroller.min.io/v1beta1
kind: MinIOInstance
metadata:
  name: matan-tarif
spec:
  metadata:
    labels:
      app: matan-tarif
  image: minio/minio:RELEASE.2020-01-03T19-12-21Z
  credsSecret:
    name: minio-creds-secret
  replicas: 4
  env:
    - name: MINIO_BROWSER
      value: "on"
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
  liveness:
    httpGet:
      path: /minio/health/live
      port: 9000
    initialDelaySeconds: 120
    periodSeconds: 20
  readiness:
    httpGet:
      path: /minio/health/ready
      port: 9000
    initialDelaySeconds: 120
    periodSeconds: 20
  volumeClaimTemplate:
    metadata:
      name: minio-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 15Gi
      storageClassName: csi-default
