apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv-rwx" 
spec:
  capacity:
    storage: "1Gi" 
  accessModes:
    - "ReadWriteMany"
  storageClassName: azure-rox
  azureFile:
    secretName: azure-storage-secret
    shareName: openshift-rwx
    readOnly: false
