apiVersion: v1
kind: Service
metadata:
  name: speedtest-download
  namespace: speedtest-cloudapp
spec:
  selector:
    app: speedtest-download
  ports:
    - name: speedtest-download
      protocol: TCP
      port: 8000
      targetPort: 8000

