kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-test-to-splunk
  namespace: app-test-to-splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test-to-splunk
  template:
    metadata:
      labels:
        app: app-test-to-splunk
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: app-test-to-splunk
            defaultMode: 420
      containers:
        - name: app-test-to-splunk
          image: '{{ .Values.containers.repository }}/{{ .Values.containers.image }}:{{ .Values.containers.version }}'
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /app-test-to-splunk/src/config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPilicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    RollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
