image:
  repository: registry.redhat.io/rh-sso-7/sso74-openshift-rhel8
  tag: 7.4

pg_image:
  repository: registry.redhat.io/rhel8/postgresql-10
  tag: latest

rhsso_namespace: rh-sso

APPLICATION_NAME: "sso"
SSO_HOSTNAME: ""
JGROUPS_CLUSTER_PASSWORD: "Aa123456"
DB_JNDI: "java:jboss/datasources/KeycloakDS"
DB_DATABASE: "testdb"
DB_USERNAME: "myuser"
DB_PASSWORD: "password"
VOLUME_CAPACITY: "1Gi"
SSO_ADMIN_USERNAME: "admin"
SSO_ADMIN_PASSWORD: "Aa123456"
SSO_REALM: ""
SSO_SERVICE_USERNAME: ""
SSO_SERVICE_PASSWORD: ""
MEMORY_LIMIT: "1Gi"
SSO_POSTGRESQL_PORT: ""
SSO_POSTGRESQL_PORT_5432_TCP: ""
SSO_POSTGRESQL_SERVICE_HOST: ""
SSO_POSTGRESQL_PORT_5432_TCP_ADDR: ""