apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - name: speedtest
        image: docker.io/dolevalgam/speedtest:latest
      hostAliases:
      - ip: "13.86.6.56"
        hostnames:
        - "speedtest-cloudapp-http.apps.ocp43-prod.cloudlet-dev.com"
