apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
  namespace: quay-enterprise
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    database:
      volumeSize: 20Gi
    enableRepoMirroring: true

# Switch to Object Storage
