apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay
  namespace: quay-enterprise
spec:
  channel: "{{ .Values.channel }}"
  name: quay
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: "{{ .Values.installPlan }}"
