apiVersion: v1
stringData:
  password: "{{.Values.password}}"
  username: "{{.Values.username}}"
kind: Secret
metadata:
  labels:
    pg-cluster: "{{.Values.cluster_name }}"
  name: "{{.Values.cluster_name}}-myuser-secret"
  namespace: "{{.Values.namespace}}"
type: Opaque
