apiVersion: crunchydata.com/v1
kind: Pgcluster
{{- with .Values  }}
metadata:
  labels:
    autofail: 'true'
    crunchy-pgbadger: 'false'
    crunchy-pgha-scope: "{{.cluster_name}}"
    crunchy_collect: 'false'
    current-primary: "{{.cluster_name}}"
    deployment-name: "{{.cluster_name}}"
    name: "{{.cluster_name}}"
    pg-cluster: "{{.cluster_name}}"
    pg-pod-anti-affinity: ''
    pgo-backrest: 'true'
    pgo-version: "{{.pgo_version}}"
    primary: 'true'
  annotations:
    current-primary: "{{.cluster_name}}"
  name: "{{.cluster_name}}"
  namespace: "{{.namespace}}"
spec:
  ArchiveStorage:
    accessmode: ''
    matchLabels: ''
    name: ''
    size: ''
    storageclass: "{{.storage_class}}"
    storagetype: dynamic
    supplementalgroups: ''
  BackrestStorage:
    accessmode: ReadWriteOnce
    matchLabels: ''
    name: ''
    size: 1G
    storageclass: "{{.storage_class}}"
    storagetype: dynamic
    supplementalgroups: ''
  ContainerResources:
    limitscpu: ''
    limitsmemory: ''
    requestscpu: ''
    requestsmemory: ''
  PrimaryStorage:
    accessmode: ReadWriteOnce
    matchLabels: ''
    name: "{{.cluster_name}}"
    size: "{{.storage_size}}"
    storageclass: "{{.storage_class}}"
    storagetype: dynamic
    supplementalgroups: ''
  ReplicaStorage:
    accessmode: ReadWriteOnce
    matchLabels: ''
    name: ''
    size: "{{.storage_size}}"
    storageclass: "{{.storage_class}}"
    storagetype: dynamic
    supplementalgroups: ''
  backuppath: ''
  backuppvcname: ''
  ccpimage: "{{.image_name}}"
  ccpimagetag: "{{.image_tag}}"
  clustername: "{{.cluster_name}}"
  customconfig: ''
  database: "{{.database_name}}"
  exporterport: '9187'
  name: "{{.cluster_name}}"
  namespace: "{{.namespace}}"
  nodename: ''
  policies: ''
  port: '5432'
  primaryhost: "{{.cluster_name}}"
  primarysecretname: "{{.cluster_name}}-primaryuser-secret"
  replicas: "{{.replicas}}"
  rootsecretname: "{{.cluster_name}}-postgres-secret"
  tls:
    caSecret: "{{.caSecret}}-postgresql-ca"
    replicationTLSSecret: ""
    tlsSecret: "{{.tlsSecret}}-hacluster-tls-keypair"
  secretfrom: ''
  status: ''
  strategy: '1'
  user: "{{.username}}"
  userlabels:
    crunchy-pgbadger: 'false'
    crunchy_collect: 'false'
    pgo-backrest: 'true'
    pgo-version: "{{.pgo_version}}"
  usersecretname: "{{.cluster_name}}-myuser-secret"
{{- end }}
