apiVersion: v1
stringData:
  password: "{{.Values.password}}"
  username: postgres
kind: Secret
metadata:
  labels:
    pg-cluster: "{{.Values.cluster_name }}"
  name: "{{.Values.cluster_name}}-postgres-secret"
  namespace: "{{.Values.namespace}}"
type: Opaque
