APPLICATION_NAME=sso
SSO_HOSTNAME=
DB_JNDI=java:jboss/datasources/KeycloakDS
DB_DATABASE=ssodb
DB_MIN_POOL_SIZE=
DB_MAX_POOL_SIZE=
DB_TX_ISOLATION=
POSTGRESQL_MAX_CONNECTIONS=
POSTGRESQL_SHARED_BUFFERS=
DB_USERNAME=admin
DB_PASSWORD=Aa123456
VOLUME_CAPACITY=1Gi
IMAGE_STREAM_NAMESPACE=openshift
SSO_ADMIN_USERNAME=admin
SSO_ADMIN_PASSWORD=Aa123456
SSO_REALM=demorealm
SSO_SERVICE_USERNAME=
SSO_SERVICE_PASSWORD=
POSTGRESQL_IMAGE_STREAM_TAG="12"
MEMORY_LIMIT=1Gi
SSO_POSTGRESQL_PORT=tcp://ssodb.pgo.svc.cluster.local:5432
SSO_POSTGRESQL_PORT_5432_TCP=tcp://ssodb.pgo.svc.cluster.local:5432
SSO_POSTGRESQL_SERVICE_HOST=ssodb.pgo.svc.cluster.local
SSO_POSTGRESQL_PORT_5432_TCP_ADDR=ssodb.pgo.svc.cluster.local
DB_SERVICE_NAME=ssodb
PG_NAMESPACE=pgo
PG_STORAGE_CLASS=managed-premium
PG_VERSION=4.3.0
PG_IMAGE_NAME=crunchy-postgres-ha
PG_IMAGE_TAG=centos7-12.2-4.3.0
PG_REPLICAS="2"
PG_STORAGE_SIZE=1G