---
- name: Running minio-operator test
  block:
    - name: Deploying YAML
      k8s:
        definition: "{{ lookup('file', 'yamls/minio-instance.yml') }}"
        state: present
        namespace: argocdod

    - name: Waiting for all MinIO StatefulSet pods to be ready
      k8s:
        kind: StatefulSet
        state: present
        name: matan-tarif
      register: statefulset_status
      until:
        - "statefulset_status.result.status.readyReplicas is defined"
        - "statefulset_status.result.spec.replicas == statefulset_status.result.status.readyReplicas"
      retries: 30
      delay: 5
    
  rescue:
     - name: Setting test error message
       set_fact:
         err_ms: "TASK: {{ ansible_failed_task.name }} FAILED WITH MSG: {{ ansible_failed_result.msg }}"
         
     - name: Updating failed_tests
       set_fact:
         failed_tests: "{{ failed_tests + [ err_ms ] }}"

  always:
    - name: Undeploy YAML
      k8s:
        definition: "{{ lookup('file', 'yamls/minio-instance.yml') }}"
        state: absent
        namespace: argocdod
