kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterloggingCR1
  labels:
    olm.owner: clusterlogging.4.2.13-201912230557
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-logging
rules:
  - verbs:
      - '*'
    apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
  - verbs:
      - '*'
    apiGroups:
      - oauth.openshift.io
    resources:
      - oauthclients
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - namespaces
