kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterloggings.crdview
  labels:
    olm.owner: clusterlogging.4.2.13-201912230557
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-logging
rules:
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - clusterloggings.logging.openshift.io
