kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterlogging
  namespace: openshift-logging
  labels:
    olm.owner: clusterlogging.4.2.13-201912230557
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-logging
rules:
  - verbs:
      - '*'
    apiGroups:
      - logging.openshift.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
      - serviceaccounts/finalizers
      - clusterloggings
      - crd
      - ClusterLogging
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - clusterloggings
      - crd
      - ClusterLogging
  - verbs:
      - '*'
    apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
  - verbs:
      - '*'
    apiGroups:
      - batch
    resources:
      - cronjobs
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
  - verbs:
      - '*'
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - prometheusrules
