kind: ConfigMap
apiVersion: v1
metadata:
  name: quay-test
  namespace: quay-test
data:
  config.py: |+
    quay_url_conf = 'https://quay.apps.{{ .Values.configmap.fqdn }}'
    quay_token = '{{ .Values.configmap.quay_auth }}'
    image = '{{ .Values.configmap.image }}'
