kind: ConfigMap
apiVersion: v1
metadata:
  name: main-test-apps
  namespace: main-test-apps
data:
  config.py: |+
    quay_url_conf = https://quay.{{ .Values.configmap.fqdn }}
    quay_auth = {{ .Values.configmap.quay_auth }}
