apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: quay-test
  namespace: quay-test
spec:
  schedule: "*/{{ .Values.every_minutes }} * * * *"
  startingDeadlineSeconds: 300
  concurrencyPolicy: "Replace"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: quay-test
              image: "quay.io/almoggo/quaytest:latest"
              env:
                - name: fqdn
                  value: {{ .Values.configmap.fqdn }}
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
