apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: quay-test
  namespace: quay-test
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 300
  concurrencyPolicy: "Replace"
  jobTemplate:
    spec:
      template:
        spec:
         volumes:
           - name: config-volume
             configMap:
               name: quay-test
               defaultMode: 420
          containers:
            - name: quay-test
              image: "quay.io/almoggo/quaytest:latest"
              env:
                - name: fqdn
                  value: {{ .Values.configmap.fqdn }}
              volumeMounts:
                - name: config-volume
                  mountPath: /quaytest/config
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
