apiVersion: v1
stringData:
  password: "{{.Values.DB_USERNAME}}"
  username: "{{.Values.DB_PASSWORD}}"
kind: Secret
metadata:
  labels:
    pg-cluster: "{{.Values.PG_CLUSTER_NAME }}"
  name: "{{.Values.PG_CLUSTER_NAME}}-myuser-secret"
  namespace: "{{.Values.PG_NAMESPACE}}"
type: Opaque
