apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  accesskey: {{ .Values.accesskey }}
  secretkey: {{ .Values.secretkey }}
