kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearches.logging.edit
rules:
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - logging.openshift.io
    resources:
      - elasticsearches
