kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearches.logging.admin
rules:
  - verbs:
      - '*'
    apiGroups:
      - logging.openshift.io
    resources:
      - elasticsearches
