kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearches.logging.admin
  labels:
    olm.owner: clusterlogging.4.2.13-201912230557
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-logging
rules:
  - verbs:
      - '*'
    apiGroups:
      - logging.openshift.io
    resources:
      - elasticsearches
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearches.logging.view
  labels:
    olm.owner: clusterlogging.4.2.13-201912230557
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-logging
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - logging.openshift.io
    resources:
      - elasticsearches
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearches.logging.edit
  labels:
    olm.owner: clusterlogging.4.2.13-201912230557
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-logging
rules:
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - logging.openshift.io
    resources:
      - elasticsearches
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearches.logging.crdview
  labels:
    olm.owner: clusterlogging.4.2.13-201912230557
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-logging
rules:
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - elasticsearches.logging.openshift.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-operatorCR
  labels:
    olm.owner: clusterlogging.4.2.13-201912230557
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-logging
rules:
  - verbs:
      - '*'
    apiGroups:
      - logging.openshift.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
  - verbs:
      - '*'
    apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
      - servicemonitors
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
  - verbs:
      - get
    nonResourceURLs:
      - /metrics
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
      - subjectaccessreviews
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews

